"""
Language Manager
Handles multi-language support for the application
"""

class LanguageManager:
    def __init__(self):
        self.current_language = "en"
        self.translations = {
            "en": {
                # Main Application
                "app_title": "Juan - Maps Scraper & WhatsApp Blaster",
                "scraper_tab": "Google Maps Scraper",
                "whatsapp_tab": "WhatsApp Blaster",
                
                # Common
                "browse": "Browse",
                "start": "Start",
                "stop": "Stop",
                "export": "Export",
                "clear": "Clear",
                "status": "Status",
                "ready": "Ready",
                "running": "Running",
                "completed": "Completed",
                "stopped": "Stopped",
                "error": "Error",
                "success": "Success",
                "warning": "Warning",
                "progress": "Progress",
                "duration": "Duration",
                "language": "Language",
                
                # Scraper Tab
                "keywords_config": "Keywords Configuration",
                "keywords_file": "Keywords File:",
                "business_count": "Business Count:",
                "scraping_controls": "Scraping Controls",
                "start_scraping": "Start Scraping",
                "stop_scraping": "Stop Scraping",
                "export_results": "Export Results",
                "scraping_status": "Scraping Status",
                "results": "Results",
                "businesses_found": "businesses found",
                "console_output": "Console Output",
                "clear_console": "Clear Console",
                "scraping": "Scraping...",
                "processing_keyword": "Processing keyword:",
                "scraping_completed": "Scraping completed. Found {} businesses.",
                "scraping_stopped": "Scraping stopped by user.",
                "error_during_scraping": "Error during scraping: {}",
                "no_keywords_found": "No keywords found in the file",
                "failed_to_read_keywords": "Failed to read keywords file: {}",
                "keywords_file_not_found": "Keywords file not found: {}",
                "starting_scraper": "Starting scraper with {} keywords",
                "no_data_to_export": "No data to export",
                "results_exported": "Results exported to: {}",
                "export_successful": "Results exported successfully to:\n{}",
                "failed_to_export": "Failed to export results: {}",
                
                # WhatsApp Tab
                "phone_import": "Phone Numbers Import",
                "csv_file": "CSV File:",
                "browse_csv": "Browse CSV",
                "load_numbers": "Load Numbers",
                "phone_validation": "Phone Validation",
                "total_numbers": "Total Numbers:",
                "valid_numbers": "Valid Numbers:",
                "invalid_numbers": "Invalid Numbers:",
                "validate_numbers": "Validate Numbers",
                "message_template": "Message Template",
                "message_content": "Message Content:",
                "sending_controls": "Sending Controls",
                "start_sending": "Start Sending",
                "stop_sending": "Stop Sending",
                "delay_seconds": "Delay (seconds):",
                "sending_status": "Sending Status",
                "status_log": "Status Log",
                "clear_log": "Clear Log",
                "select_csv_file": "Please select a CSV file first",
                "loaded_numbers": "Loaded {} phone numbers from CSV",
                "no_phone_numbers_found": "No phone numbers found in the CSV file",
                "failed_to_load_csv": "Failed to load CSV file: {}",
                "no_phone_numbers_loaded": "No phone numbers loaded",
                "validation_complete": "Validation complete: {} valid, {} invalid",
                "found_valid_numbers": "Found {} valid phone numbers",
                "no_valid_numbers": "No valid phone numbers found",
                "no_valid_numbers_available": "No valid phone numbers available",
                "enter_message": "Please enter a message",
                "confirm_sending": "Send message to {} phone numbers?\n\nThis will open WhatsApp Web in Chrome.",
                "sending": "Sending...",
                "starting_send": "Starting to send messages to {} numbers",
                "sending_message_to": "Sending message to {}",
                "message_sent_to": "Message sent to {} successfully",
                "sending_completed": "Sending completed. {} messages sent.",
                "sending_stopped": "Sending stopped by user.",
                "error_during_sending": "Error during sending: {}",
                "stopping_send": "Stopping message sending...",
                "default_message": "Hello! This is a business inquiry message. Please let me know if you're interested in our services."
            },
            
            "tr": {
                # Main Application
                "app_title": "Juan - Harita Kazıyıcı & WhatsApp Gönderici",
                "scraper_tab": "Google Harita Kazıyıcı",
                "whatsapp_tab": "WhatsApp Gönderici",
                
                # Common
                "browse": "Gözat",
                "start": "Başlat",
                "stop": "Durdur",
                "export": "Dışa Aktar",
                "clear": "Temizle",
                "status": "Durum",
                "ready": "Hazır",
                "running": "Çalışıyor",
                "completed": "Tamamlandı",
                "stopped": "Durduruldu",
                "error": "Hata",
                "success": "Başarılı",
                "warning": "Uyarı",
                "progress": "İlerleme",
                "duration": "Süre",
                "language": "Dil",
                
                # Scraper Tab
                "keywords_config": "Anahtar Kelime Yapılandırması",
                "keywords_file": "Anahtar Kelime Dosyası:",
                "business_count": "İşletme Sayısı:",
                "scraping_controls": "Kazıma Kontrolleri",
                "start_scraping": "Kazımayı Başlat",
                "stop_scraping": "Kazımayı Durdur",
                "export_results": "Sonuçları Dışa Aktar",
                "scraping_status": "Kazıma Durumu",
                "results": "Sonuçlar",
                "businesses_found": "işletme bulundu",
                "console_output": "Konsol Çıktısı",
                "clear_console": "Konsolu Temizle",
                "scraping": "Kazıyor...",
                "processing_keyword": "Anahtar kelime işleniyor:",
                "scraping_completed": "Kazıma tamamlandı. {} işletme bulundu.",
                "scraping_stopped": "Kazıma kullanıcı tarafından durduruldu.",
                "error_during_scraping": "Kazıma sırasında hata: {}",
                "no_keywords_found": "Dosyada anahtar kelime bulunamadı",
                "failed_to_read_keywords": "Anahtar kelime dosyası okunamadı: {}",
                "keywords_file_not_found": "Anahtar kelime dosyası bulunamadı: {}",
                "starting_scraper": "{} anahtar kelime ile kazıyıcı başlatılıyor",
                "no_data_to_export": "Dışa aktarılacak veri yok",
                "results_exported": "Sonuçlar şuraya aktarıldı: {}",
                "export_successful": "Sonuçlar başarıyla şuraya aktarıldı:\n{}",
                "failed_to_export": "Sonuçları dışa aktarma başarısız: {}",
                
                # WhatsApp Tab
                "phone_import": "Telefon Numarası İçe Aktarma",
                "csv_file": "CSV Dosyası:",
                "browse_csv": "CSV Gözat",
                "load_numbers": "Numaraları Yükle",
                "phone_validation": "Telefon Doğrulama",
                "total_numbers": "Toplam Numara:",
                "valid_numbers": "Geçerli Numara:",
                "invalid_numbers": "Geçersiz Numara:",
                "validate_numbers": "Numaraları Doğrula",
                "message_template": "Mesaj Şablonu",
                "message_content": "Mesaj İçeriği:",
                "sending_controls": "Gönderim Kontrolleri",
                "start_sending": "Gönderimi Başlat",
                "stop_sending": "Gönderimi Durdur",
                "delay_seconds": "Gecikme (saniye):",
                "sending_status": "Gönderim Durumu",
                "status_log": "Durum Günlüğü",
                "clear_log": "Günlüğü Temizle",
                "select_csv_file": "Lütfen önce bir CSV dosyası seçin",
                "loaded_numbers": "CSV'den {} telefon numarası yüklendi",
                "no_phone_numbers_found": "CSV dosyasında telefon numarası bulunamadı",
                "failed_to_load_csv": "CSV dosyası yüklenemedi: {}",
                "no_phone_numbers_loaded": "Yüklenen telefon numarası yok",
                "validation_complete": "Doğrulama tamamlandı: {} geçerli, {} geçersiz",
                "found_valid_numbers": "{} geçerli telefon numarası bulundu",
                "no_valid_numbers": "Geçerli telefon numarası bulunamadı",
                "no_valid_numbers_available": "Geçerli telefon numarası yok",
                "enter_message": "Lütfen bir mesaj girin",
                "confirm_sending": "{} telefon numarasına mesaj gönderilsin mi?\n\nBu, Chrome'da WhatsApp Web'i açacak.",
                "sending": "Gönderiyor...",
                "starting_send": "{} numaraya mesaj gönderimi başlatılıyor",
                "sending_message_to": "{} numarasına mesaj gönderiliyor",
                "message_sent_to": "{} numarasına mesaj başarıyla gönderildi",
                "sending_completed": "Gönderim tamamlandı. {} mesaj gönderildi.",
                "sending_stopped": "Gönderim kullanıcı tarafından durduruldu.",
                "error_during_sending": "Gönderim sırasında hata: {}",
                "stopping_send": "Mesaj gönderimi durduruluyor...",
                "default_message": "Merhaba! Bu bir işletme sorgulama mesajıdır. Hizmetlerimizle ilgilenip ilgilenmediğinizi lütfen bana bildirin."
            },
            
            "ar": {
                # Main Application
                "app_title": "خوان - كاشط الخرائط ومرسل واتساب",
                "scraper_tab": "كاشط خرائط جوجل",
                "whatsapp_tab": "مرسل واتساب",
                
                # Common
                "browse": "تصفح",
                "start": "بدء",
                "stop": "إيقاف",
                "export": "تصدير",
                "clear": "مسح",
                "status": "الحالة",
                "ready": "جاهز",
                "running": "يعمل",
                "completed": "مكتمل",
                "stopped": "متوقف",
                "error": "خطأ",
                "success": "نجح",
                "warning": "تحذير",
                "progress": "التقدم",
                "duration": "المدة",
                "language": "اللغة",
                
                # Scraper Tab
                "keywords_config": "تكوين الكلمات المفتاحية",
                "keywords_file": "ملف الكلمات المفتاحية:",
                "business_count": "عدد الأعمال:",
                "scraping_controls": "ضوابط الكشط",
                "start_scraping": "بدء الكشط",
                "stop_scraping": "إيقاف الكشط",
                "export_results": "تصدير النتائج",
                "scraping_status": "حالة الكشط",
                "results": "النتائج",
                "businesses_found": "شركة موجودة",
                "console_output": "إخراج وحدة التحكم",
                "clear_console": "مسح وحدة التحكم",
                "scraping": "يكشط...",
                "processing_keyword": "معالجة الكلمة المفتاحية:",
                "scraping_completed": "اكتمل الكشط. تم العثور على {} شركة.",
                "scraping_stopped": "تم إيقاف الكشط من قبل المستخدم.",
                "error_during_scraping": "خطأ أثناء الكشط: {}",
                "no_keywords_found": "لم يتم العثور على كلمات مفتاحية في الملف",
                "failed_to_read_keywords": "فشل في قراءة ملف الكلمات المفتاحية: {}",
                "keywords_file_not_found": "ملف الكلمات المفتاحية غير موجود: {}",
                "starting_scraper": "بدء الكاشط بـ {} كلمة مفتاحية",
                "no_data_to_export": "لا توجد بيانات للتصدير",
                "results_exported": "تم تصدير النتائج إلى: {}",
                "export_successful": "تم تصدير النتائج بنجاح إلى:\n{}",
                "failed_to_export": "فشل في تصدير النتائج: {}",
                
                # WhatsApp Tab
                "phone_import": "استيراد أرقام الهواتف",
                "csv_file": "ملف CSV:",
                "browse_csv": "تصفح CSV",
                "load_numbers": "تحميل الأرقام",
                "phone_validation": "التحقق من الهاتف",
                "total_numbers": "إجمالي الأرقام:",
                "valid_numbers": "أرقام صالحة:",
                "invalid_numbers": "أرقام غير صالحة:",
                "validate_numbers": "التحقق من الأرقام",
                "message_template": "قالب الرسالة",
                "message_content": "محتوى الرسالة:",
                "sending_controls": "ضوابط الإرسال",
                "start_sending": "بدء الإرسال",
                "stop_sending": "إيقاف الإرسال",
                "delay_seconds": "التأخير (ثواني):",
                "sending_status": "حالة الإرسال",
                "status_log": "سجل الحالة",
                "clear_log": "مسح السجل",
                "select_csv_file": "يرجى تحديد ملف CSV أولاً",
                "loaded_numbers": "تم تحميل {} رقم هاتف من CSV",
                "no_phone_numbers_found": "لم يتم العثور على أرقام هواتف في ملف CSV",
                "failed_to_load_csv": "فشل في تحميل ملف CSV: {}",
                "no_phone_numbers_loaded": "لم يتم تحميل أرقام هواتف",
                "validation_complete": "اكتمل التحقق: {} صالح، {} غير صالح",
                "found_valid_numbers": "تم العثور على {} رقم هاتف صالح",
                "no_valid_numbers": "لم يتم العثور على أرقام هواتف صالحة",
                "no_valid_numbers_available": "لا توجد أرقام هواتف صالحة متاحة",
                "enter_message": "يرجى إدخال رسالة",
                "confirm_sending": "إرسال رسالة إلى {} رقم هاتف؟\n\nسيفتح هذا واتساب ويب في كروم.",
                "sending": "يرسل...",
                "starting_send": "بدء إرسال الرسائل إلى {} رقم",
                "sending_message_to": "إرسال رسالة إلى {}",
                "message_sent_to": "تم إرسال الرسالة إلى {} بنجاح",
                "sending_completed": "اكتمل الإرسال. تم إرسال {} رسالة.",
                "sending_stopped": "تم إيقاف الإرسال من قبل المستخدم.",
                "error_during_sending": "خطأ أثناء الإرسال: {}",
                "stopping_send": "إيقاف إرسال الرسائل...",
                "default_message": "مرحباً! هذه رسالة استفسار تجاري. يرجى إعلامي إذا كنت مهتماً بخدماتنا."
            },
            
            "es": {
                # Main Application
                "app_title": "Juan - Raspador de Mapas y Emisor de WhatsApp",
                "scraper_tab": "Raspador de Google Maps",
                "whatsapp_tab": "Emisor de WhatsApp",
                
                # Common
                "browse": "Navegar",
                "start": "Iniciar",
                "stop": "Detener",
                "export": "Exportar",
                "clear": "Limpiar",
                "status": "Estado",
                "ready": "Listo",
                "running": "Ejecutándose",
                "completed": "Completado",
                "stopped": "Detenido",
                "error": "Error",
                "success": "Éxito",
                "warning": "Advertencia",
                "progress": "Progreso",
                "duration": "Duración",
                "language": "Idioma",
                
                # Scraper Tab
                "keywords_config": "Configuración de Palabras Clave",
                "keywords_file": "Archivo de Palabras Clave:",
                "business_count": "Cantidad de Negocios:",
                "scraping_controls": "Controles de Raspado",
                "start_scraping": "Iniciar Raspado",
                "stop_scraping": "Detener Raspado",
                "export_results": "Exportar Resultados",
                "scraping_status": "Estado del Raspado",
                "results": "Resultados",
                "businesses_found": "negocios encontrados",
                "console_output": "Salida de Consola",
                "clear_console": "Limpiar Consola",
                "scraping": "Raspando...",
                "processing_keyword": "Procesando palabra clave:",
                "scraping_completed": "Raspado completado. Se encontraron {} negocios.",
                "scraping_stopped": "Raspado detenido por el usuario.",
                "error_during_scraping": "Error durante el raspado: {}",
                "no_keywords_found": "No se encontraron palabras clave en el archivo",
                "failed_to_read_keywords": "Error al leer el archivo de palabras clave: {}",
                "keywords_file_not_found": "Archivo de palabras clave no encontrado: {}",
                "starting_scraper": "Iniciando raspador con {} palabras clave",
                "no_data_to_export": "No hay datos para exportar",
                "results_exported": "Resultados exportados a: {}",
                "export_successful": "Resultados exportados exitosamente a:\n{}",
                "failed_to_export": "Error al exportar resultados: {}",
                
                # WhatsApp Tab
                "phone_import": "Importación de Números de Teléfono",
                "csv_file": "Archivo CSV:",
                "browse_csv": "Navegar CSV",
                "load_numbers": "Cargar Números",
                "phone_validation": "Validación de Teléfono",
                "total_numbers": "Números Totales:",
                "valid_numbers": "Números Válidos:",
                "invalid_numbers": "Números Inválidos:",
                "validate_numbers": "Validar Números",
                "message_template": "Plantilla de Mensaje",
                "message_content": "Contenido del Mensaje:",
                "sending_controls": "Controles de Envío",
                "start_sending": "Iniciar Envío",
                "stop_sending": "Detener Envío",
                "delay_seconds": "Retraso (segundos):",
                "sending_status": "Estado de Envío",
                "status_log": "Registro de Estado",
                "clear_log": "Limpiar Registro",
                "select_csv_file": "Por favor seleccione un archivo CSV primero",
                "loaded_numbers": "Se cargaron {} números de teléfono desde CSV",
                "no_phone_numbers_found": "No se encontraron números de teléfono en el archivo CSV",
                "failed_to_load_csv": "Error al cargar archivo CSV: {}",
                "no_phone_numbers_loaded": "No se cargaron números de teléfono",
                "validation_complete": "Validación completa: {} válidos, {} inválidos",
                "found_valid_numbers": "Se encontraron {} números de teléfono válidos",
                "no_valid_numbers": "No se encontraron números de teléfono válidos",
                "no_valid_numbers_available": "No hay números de teléfono válidos disponibles",
                "enter_message": "Por favor ingrese un mensaje",
                "confirm_sending": "¿Enviar mensaje a {} números de teléfono?\n\nEsto abrirá WhatsApp Web en Chrome.",
                "sending": "Enviando...",
                "starting_send": "Iniciando envío de mensajes a {} números",
                "sending_message_to": "Enviando mensaje a {}",
                "message_sent_to": "Mensaje enviado a {} exitosamente",
                "sending_completed": "Envío completado. {} mensajes enviados.",
                "sending_stopped": "Envío detenido por el usuario.",
                "error_during_sending": "Error durante el envío: {}",
                "stopping_send": "Deteniendo envío de mensajes...",
                "default_message": "¡Hola! Este es un mensaje de consulta comercial. Por favor, háganme saber si están interesados en nuestros servicios."
            },
            
            "fr": {
                # Main Application
                "app_title": "Juan - Extracteur de Cartes et Émetteur WhatsApp",
                "scraper_tab": "Extracteur Google Maps",
                "whatsapp_tab": "Émetteur WhatsApp",
                
                # Common
                "browse": "Parcourir",
                "start": "Démarrer",
                "stop": "Arrêter",
                "export": "Exporter",
                "clear": "Effacer",
                "status": "Statut",
                "ready": "Prêt",
                "running": "En cours",
                "completed": "Terminé",
                "stopped": "Arrêté",
                "error": "Erreur",
                "success": "Succès",
                "warning": "Avertissement",
                "progress": "Progrès",
                "duration": "Durée",
                "language": "Langue",
                
                # Scraper Tab
                "keywords_config": "Configuration des Mots-clés",
                "keywords_file": "Fichier de Mots-clés:",
                "business_count": "Nombre d'Entreprises:",
                "scraping_controls": "Contrôles d'Extraction",
                "start_scraping": "Démarrer l'Extraction",
                "stop_scraping": "Arrêter l'Extraction",
                "export_results": "Exporter les Résultats",
                "scraping_status": "Statut d'Extraction",
                "results": "Résultats",
                "businesses_found": "entreprises trouvées",
                "console_output": "Sortie Console",
                "clear_console": "Effacer la Console",
                "scraping": "Extraction...",
                "processing_keyword": "Traitement du mot-clé:",
                "scraping_completed": "Extraction terminée. {} entreprises trouvées.",
                "scraping_stopped": "Extraction arrêtée par l'utilisateur.",
                "error_during_scraping": "Erreur pendant l'extraction: {}",
                "no_keywords_found": "Aucun mot-clé trouvé dans le fichier",
                "failed_to_read_keywords": "Échec de lecture du fichier de mots-clés: {}",
                "keywords_file_not_found": "Fichier de mots-clés non trouvé: {}",
                "starting_scraper": "Démarrage de l'extracteur avec {} mots-clés",
                "no_data_to_export": "Aucune donnée à exporter",
                "results_exported": "Résultats exportés vers: {}",
                "export_successful": "Résultats exportés avec succès vers:\n{}",
                "failed_to_export": "Échec de l'exportation des résultats: {}",
                
                # WhatsApp Tab
                "phone_import": "Importation des Numéros de Téléphone",
                "csv_file": "Fichier CSV:",
                "browse_csv": "Parcourir CSV",
                "load_numbers": "Charger les Numéros",
                "phone_validation": "Validation du Téléphone",
                "total_numbers": "Numéros Totaux:",
                "valid_numbers": "Numéros Valides:",
                "invalid_numbers": "Numéros Invalides:",
                "validate_numbers": "Valider les Numéros",
                "message_template": "Modèle de Message",
                "message_content": "Contenu du Message:",
                "sending_controls": "Contrôles d'Envoi",
                "start_sending": "Démarrer l'Envoi",
                "stop_sending": "Arrêter l'Envoi",
                "delay_seconds": "Délai (secondes):",
                "sending_status": "Statut d'Envoi",
                "status_log": "Journal de Statut",
                "clear_log": "Effacer le Journal",
                "select_csv_file": "Veuillez d'abord sélectionner un fichier CSV",
                "loaded_numbers": "{} numéros de téléphone chargés depuis CSV",
                "no_phone_numbers_found": "Aucun numéro de téléphone trouvé dans le fichier CSV",
                "failed_to_load_csv": "Échec du chargement du fichier CSV: {}",
                "no_phone_numbers_loaded": "Aucun numéro de téléphone chargé",
                "validation_complete": "Validation terminée: {} valides, {} invalides",
                "found_valid_numbers": "{} numéros de téléphone valides trouvés",
                "no_valid_numbers": "Aucun numéro de téléphone valide trouvé",
                "no_valid_numbers_available": "Aucun numéro de téléphone valide disponible",
                "enter_message": "Veuillez entrer un message",
                "confirm_sending": "Envoyer message à {} numéros de téléphone?\n\nCeci ouvrira WhatsApp Web dans Chrome.",
                "sending": "Envoi...",
                "starting_send": "Démarrage de l'envoi de messages à {} numéros",
                "sending_message_to": "Envoi du message à {}",
                "message_sent_to": "Message envoyé à {} avec succès",
                "sending_completed": "Envoi terminé. {} messages envoyés.",
                "sending_stopped": "Envoi arrêté par l'utilisateur.",
                "error_during_sending": "Erreur pendant l'envoi: {}",
                "stopping_send": "Arrêt de l'envoi de messages...",
                "default_message": "Bonjour ! Ceci est un message de demande commerciale. Veuillez me faire savoir si vous êtes intéressé par nos services."
            }
        }
    
    def set_language(self, language_code):
        """Set the current language"""
        if language_code in self.translations:
            self.current_language = language_code
            return True
        return False
    
    def get_languages(self):
        """Get available languages"""
        return {
            "en": "English",
            "tr": "Türkçe",
            "ar": "العربية",
            "es": "Español",
            "fr": "Français"
        }
    
    def get_text(self, key):
        """Get translated text for the current language"""
        if self.current_language in self.translations:
            return self.translations[self.current_language].get(key, key)
        return key
    
    def get_current_language(self):
        """Get current language code"""
        return self.current_language
    
    def get_available_languages(self):
        """Get available languages dictionary (alias for get_languages)"""
        return self.get_languages()